### ISSUE TITLE
getting Auto hotkey path error, but AHK is in Default instal location.

### ISSUE THREAD

**Issue by TheCodeingPadawan** [spyoungtech/helldivers2-macros#5] opened 2024-03-31 07:50 UTC
I'm getting the following error.

```
Traceback (most recent call last):
  File "hd2_macros\__main__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "hd2_macros\macro.py", line 18, in <module>
  File "ahk\_sync\engine.py", line 165, in __init__
  File "ahk\_utils.py", line 114, in _resolve_executable_path
ahk._utils.AhkExecutableNotFoundError: Could not find AutoHotkey.exe on PATH. Provide the absolute path with the `executable_path` keyword argument or in the AHK_PATH environment variable. You can likely resolve this error simply by installing the binary extra with the following command:
        pip install "ahk[binary]"
[23984] Failed to execute script '__main__' due to unhandled exception!

[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

I do not understand as AHK is in its default install location.

C:\Program Files\AutoHotkey\v2\AutoHotkey64.exe
C:\Program Files\AutoHotkey\AutoHotkey.exe

**Comment by TheCodeingPadawan** [comment] 2024-03-31 08:18
FIXED.

Had to add new system environment variable "AHK_PATH" And point to the AHK directory.
should also make it clear that it needs to run as an administrator, Or you get an access denied error when trying to find the window.

**Comment by spyoungtech** [comment] 2024-04-01 01:25
Thanks for the report. Glad you were able to figure that out. I can probably make this a bit more reliable.

**Comment by spyoungtech** [comment] 2024-04-01 18:45
@TheCodeingPadawan can you provide the traceback you receive for the Access Denied error when not running as an administrator? I'm not able to reproduce that issue.

**Comment by spyoungtech** [comment] 2024-04-05 03:47
Ok. I realize what the issue is around the Access Denied issue. If you have another application window running as an administrator, getting its process path will fail with a permission error. This can be worked around.

The issue with the default install location is that only AutoHotkey v1 paths are recognized by default. I will make this configurable in this project.

**Comment by spyoungtech** [comment] 2024-04-05 08:07
This should now be resolved in the latest release. You should be able to run without setting the environment variable or running as an administrator (as long as helldivers2 is not being run as an administrator).

**Closed as completed by spyoungtech** 2024-04-05 08:07 UTC
